---
settings:
  name: ONTAP
  search: ontap,ontap-cli,ontap-automation,ontap-metrocluster,ontap-systems-switches,ontap-technical-reports,ontap-sanhost,asa-r2
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione del prodotto ONTAP
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Tutto
    tags: all
    class: active
  - title: Automazione
    tags: automation
  - title: Gestione dei dati
    tags: management
  - title: Migrazione dei dati
    tags: migration
  - title: Protezione dei dati
    tags: protection
  - title: Sistemi hardware
    tags: hardware
  tiles:
  - title: ONTAP 9 per sistemi AFF, ASA e FAS
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap/index.html
    summary: Utilizza il software ONTAP per gestire i dati su sistemi FAS all-flash,
      sistemi SAN array all-flash e array flash ibridi FAS.
    tags: all, management, protection
  - title: Sistemi AFF, ASA e FAS
    icon: "./media/groups_line.png"
    url: https://docs.netapp.com/us-en/ontap-systems-family/
    summary: Scopri come installare, mantenere e aggiornare i sistemi FAS all-flash,
      i sistemi array SAN all-flash e gli array flash ibridi FAS.
    tags: all, hardware
  - title: Sistemi ASA r2
    icon: "./media/groups_line.png"
    url: https://docs.netapp.com/us-en/asa-r2/index.html
    summary: Installa il sistema ASA R2 e usa ONTAP per gestire i dati.
    tags: all, hardware
  - title: ONTAP MetroCluster
    icon: "./media/metrocluster.png"
    url: https://docs.netapp.com/us-en/ontap-metrocluster/
    summary: Proteggi il tuo storage utilizzando il clustering basato su array con
      replica sincrona per offrire una disponibilità continua.
    tags: all, protection
  - title: Configurazione dell'host SAN ONTAP
    icon: "./media/server.png"
    url: https://docs.netapp.com/us-en/ontap-sanhost/
    summary: Configurare gli host SAN ONTAP per i protocolli NVMe, iSCSI e FC.
    tags: all, management
  - title: Report tecnici ONTAP
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap-technical-reports/index.html
    summary: Scopri di più sull'architettura ONTAP e su come ottimizzare ONTAP per
      carichi di lavoro e ambienti specifici.
    tags: all, management, protection
  - title: Comandi ONTAP
    icon: "./media/cli.png"
    url: https://docs.netapp.com/us-en/ontap-cli/
    summary: Scopri i comandi disponibili nella CLI di ONTAP.
    tags: all, management
  - title: Riferimento EMS ONTAP
    icon: "./media/cli.png"
    url: https://docs.netapp.com/us-en/ontap-ems-9141/
    summary: Scopri di più sugli eventi del sistema di messaggistica degli eventi
      (EMS) in ONTAP.
    tags: all, management
  - title: Automazione ONTAP
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/ontap-automation/index.html
    summary: Automatizza l'implementazione e l'amministrazione dei sistemi storage
      ONTAP utilizzando l'API REST di ONTAP e le tecnologie di supporto.
    tags: all, automation, management
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
    summary: Implementa un'istanza virtuale di ONTAP per rendere lo storage cloud
      più conveniente, intelligente, conforme e sicuro.
    tags: all, management, protection
  - title: ONTAP Select
    icon: "./media/server.png"
    url: https://docs.netapp.com/us-en/ontap-select/
    summary: Implementa ONTAP come appliance di storage software-defined su una vasta
      gamma di server hardware commodity che eseguono l'hypervisor VMware ESXi.
    tags: all, management, protection
  - title: Importazione LUN esterna ONTAP
    icon: "./media/transition-tools.png"
    url: https://docs.netapp.com/us-en/ontap-fli/
    summary: Migra le LUN da array di terze parti e sistemi 7-Mode al moderno storage
      NetApp.
    tags: all, migration
